; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[platformio]
default_envs = esp32dev

[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
test_framework = unity
test_build_src = yes
build_flags = -std=gnu++17
lib_deps = olikraus/U8g2@^2.36.15

[env:seeed_xiao-esp32c3]
platform = https://github.com/pioarduino/platform-espressif32/releases/download/54.03.21/platform-espressif32.zip
platform_packages = 
	framework-arduinoespressif32 @ https://github.com/espressif/arduino-esp32.git#3.2.1
board = seeed_xiao_esp32c3
board_build.f_cpu = 160000000L
upload_speed = 921600
monitor_speed = 115200
framework = arduino
board_build.filesystem = littlefs
board_build.partitions = partition_table.csv
build_type = release
build_unflags = -Os
build_flags = 
	-std=gnu++17
	-O3
	-D CORE_DEBUG_LEVEL=0
lib_deps = olikraus/U8g2@^2.36.15

[env:super-mini-k2]
extends = env:seeed_xiao-esp32c3
board = nologo_esp32c3_super_mini

[env:native]
platform = native
test_framework = unity
test_build_src = yes
build_src_filter = +<*> -<main.cpp>
build_flags = 
	-I src
	-I test/stubs
lib_deps = olikraus/U8g2@^2.36.15
